# Creating Dataframe

In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
} 
df =pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
data_list = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
} 
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#selecting and indexing of columns

In [19]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [20]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [22]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [23]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [27]:
df2["Designation"] = ['Doctor','Engineer','Doctor','Engineer']

In [28]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

#Remove the column

In [35]:
df2.drop('Designation',axis = 1,inplace = True)

In [36]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting Row

In [39]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [40]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subset of rows and columns

In [41]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [42]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Statement

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
#condition :- i only want to see those people whose age is above 30

In [45]:
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [57]:
df2([df2['Age']>30]) & (df2["City"] == "Paris")

TypeError: '>' not supported between instances of 'str' and 'int'